---
title: "NFL Stadium Locations"
author: "Jacob M. Lundeen"
date: "2023-03-21"
output: ioslides_presentation
---

```{r setup, include=FALSE, echo = FALSE, message = FALSE, warnings = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(geosphere)
library(leaflet)
```

```{r, results='hide'}
nflLatLong <- read.csv("NFLData.csv")
teamIcons <- icons(
  iconUrl = nflLatLong$Logos,
  iconWidth = 40*215/230, iconHeight = 31, iconAnchorX = 31*215/230/2,
  iconAnchorY = 16
  )
```

## All 32 NFL Stadiums

```{r}
leaflet() %>%
  addTiles() %>%
  addMarkers(data = nflLatLong,
             lng = ~longitude,
             lat = ~latitude,
             clusterOptions = markerClusterOptions(),
             icon = teamIcons, 
             label = ~Team,
             popup = ~paste("<br>Conference:", Conference,
                            "<br>State:", State,
                            "<br>Number of SBs:", SBs)
             )
```

## National Football Conference Stadiums

```{r}
nfcSubset = subset(nflLatLong, Conference == "NFC")
nfcIcons <- icons(
  iconUrl = nfcSubset$Logos,
  iconWidth = 40*215/230, iconHeight = 31, iconAnchorX = 31*215/230/2,
  iconAnchorY = 16
)
leaflet() %>%
  addTiles() %>%
  addMarkers(data = nfcSubset,
             lng = ~longitude,
             lat = ~latitude,
             clusterOptions = markerClusterOptions(),
             icon = nfcIcons, 
             label = ~Team,
             popup = ~paste("<br>Conference:", Conference,
                            "<br>State:", State,
                            "<br>Number of SBs:", SBs)
             )
```

## NFC North Division Stadiums

```{r}
nfcNSubset = subset(nfcSubset, Division == "North")
nfcNIcons <- icons(
  iconUrl = nfcNSubset$Logos,
  iconWidth = 40*215/230, iconHeight = 31, iconAnchorX = 31*215/230/2,
  iconAnchorY = 16
)
area <- round(areaPolygon(as.matrix(nfcNSubset[,5:4])) * (3.861 * 10^(-7)), 2)
leaflet() %>%
  addTiles() %>%
  addPolygons(lng = nfcNSubset$longitude, lat = nfcNSubset$latitude, 
              popup = paste("Area:", area, "mi<sup>2")) %>%
  addMarkers(data = nfcNSubset,
             lng = ~longitude,
             lat = ~latitude,
             clusterOptions = markerClusterOptions(),
             icon = nfcNIcons, 
             label = ~Team,
             popup = ~paste("<br>Conference:", Conference,
                            "<br>State:", State,
                            "<br>Number of SBs:", SBs)
             )
```

## NFC South Division Stadiums

```{r}
nfcSSubset = subset(nfcSubset, Division == "South")
rownames(nfcSSubset)<-1:nrow(nfcSSubset)
nfcSSubset <- nfcSSubset[c(1,3,2,4),]
nfcSIcons <- icons(
  iconUrl = nfcSSubset$Logos,
  iconWidth = 40*215/230, iconHeight = 31, iconAnchorX = 31*215/230/2,
  iconAnchorY = 16
)
area <- round(areaPolygon(as.matrix(nfcSSubset[,5:4])) * (3.861 * 10^(-7)), 2)
leaflet() %>%
  addTiles() %>%
  addPolygons(lng = nfcSSubset$longitude, lat = nfcSSubset$latitude, 
              popup = paste("Area:", area, "mi<sup>2")) %>%
  addMarkers(data = nfcSSubset,
             lng = ~longitude,
             lat = ~latitude,
             clusterOptions = markerClusterOptions(),
             icon = nfcSIcons, 
             label = ~Team,
             popup = ~paste("<br>Conference:", Conference,
                            "<br>State:", State,
                            "<br>Number of SBs:", SBs)
             )
```

## NFC East Division Stadiums

```{r}
nfcESubset = subset(nfcSubset, Division == "East")
rownames(nfcESubset)<-1:nrow(nfcESubset)
nfcESubset <- nfcESubset[c(1,2,4,3),]
nfcEIcons <- icons(
  iconUrl = nfcESubset$Logos,
  iconWidth = 40*215/230, iconHeight = 31, iconAnchorX = 31*215/230/2,
  iconAnchorY = 16
)
area <- round(areaPolygon(as.matrix(nfcESubset[,5:4])) * (3.861 * 10^(-7)), 2)
leaflet() %>%
  addTiles() %>%
  addPolygons(lng = nfcESubset$longitude, lat = nfcESubset$latitude, 
              popup = paste("Area:", area, "mi<sup>2")) %>%
  addMarkers(data = nfcESubset,
             lng = ~longitude,
             lat = ~latitude,
             clusterOptions = markerClusterOptions(),
             icon = nfcEIcons, 
             label = ~Team,
             popup = ~paste("<br>Conference:", Conference,
                            "<br>State:", State,
                            "<br>Number of SBs:", SBs)
             )
```

## NFC West Division Stadiums

```{r}
nfcWSubset = subset(nfcSubset, Division == "West")
rownames(nfcWSubset)<-1:nrow(nfcWSubset)
nfcWSubset <- nfcWSubset[c(1,3,2,4),]
nfcWIcons <- icons(
  iconUrl = nfcWSubset$Logos,
  iconWidth = 40*215/230, iconHeight = 31, iconAnchorX = 31*215/230/2,
  iconAnchorY = 16
)
area <- round(areaPolygon(as.matrix(nfcWSubset[,5:4])) * (3.861 * 10^(-7)), 2)
leaflet() %>%
  addTiles() %>%
  addPolygons(lng = nfcWSubset$longitude, lat = nfcWSubset$latitude, 
              popup = paste("Area:", area, "mi<sup>2")) %>%
  addMarkers(data = nfcWSubset,
             lng = ~longitude,
             lat = ~latitude,
             clusterOptions = markerClusterOptions(),
             icon = nfcWIcons, 
             label = ~Team,
             popup = ~paste("<br>Conference:", Conference,
                            "<br>State:", State,
                            "<br>Number of SBs:", SBs)
             )
```

## American Football Conference Stadiums

```{r}
afcSubset = subset(nflLatLong, Conference == "AFC")
afcIcons <- icons(
  iconUrl = afcSubset$Logos,
  iconWidth = 40*215/230, iconHeight = 31, iconAnchorX = 31*215/230/2,
  iconAnchorY = 16
)
leaflet() %>%
  addTiles() %>%
  addMarkers(data = afcSubset,
             lng = ~longitude,
             lat = ~latitude,
             clusterOptions = markerClusterOptions(),
             icon = afcIcons, 
             label = ~Team,
             popup = ~paste("<br>Conference:", Conference,
                            "<br>State:", State,
                            "<br>Number of SBs:", SBs)
             )
```